# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          repository: CERT-Polska/drakvuf-sandbox
          ref: ops-ipt
          path: sandbox
          submodules: false
      - name: Get DRAKVUF commit ref
        id: get_drakvuf_ref
        run: |
          DRAKVUF_REF=$(sh -c 'cd sandbox && git ls-tree HEAD drakvuf' | cut -f3 '-d ' | cut -f1 -d$'\t')
          echo "::set-output name=drakvuf_ref::${DRAKVUF_REF}"
      - name: Checkout DRAKVUF
        uses: actions/checkout@v2
        with:
          repository: tklengyel/drakvuf
          path: drakvuf
          ref: ${{ steps.get_drakvuf_ref.outputs.drakvuf_ref }}
          submodules: recursive
      - name: Build DRAKVUF package
        id: build_drakvuf_deb
        run: |
          sh -c 'cd drakvuf && sh package/build.sh ${{ matrix.container }}'
          DRAKVUF_DEB_PATH=$(find drakvuf/package/out/*.deb | head -n1)
          DRAKVUF_DEB_NAME=$(basename "$DRAKVUF_DEB_PATH")
          echo "::set-output name=drakvuf_deb_path::${DRAKVUF_DEB_PATH}"
          echo "::set-output name=drakvuf_deb_name::${{ steps.gen_vars.outputs.artifact_prefix }}_${DRAKVUF_DEB_NAME}"
